#version: '3.8'

services:
  # PSSS Laravel Application
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: psss-app
    volumes:
      - ./:/var/www/html/phpsitespellchecker
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/phpsitespellchecker
    depends_on:
      - mysql
    networks:
      - psss-net

  # PSSS LanguageTool server
  languagetool:
    image: erikvl87/languagetool
    container_name: psss-lt
    ports:
      - "8081:8010"

  # MySQL Database
  mysql:
    image: mysql:8.4.0-oraclelinux8
    container_name: psss-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:  psss
      MYSQL_DATABASE: psss
      MYSQL_USER: psss
      MYSQL_PASSWORD: psss
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - psss-net

networks:
  psss-net:
